# publish-nuget.yml
name: Publish NuGet Package on Push to Main

on:
  push:
    branches:
      - main

jobs:
  Package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"

      - name: Build DotNet
        # You may pin to the exact commit or the version.
        # uses: Elskom/build-dotnet@54d97a0f7d5d5ca946404976db00d27386b09254
        uses: Elskom/build-dotnet@v1.1.1
        with:
          # Filepath of the solution of which contains all the projects to be built, optionally tested and packed, relative to root of repository
          SOLUTION_FILE_PATH: ./
          # Flag to toggle running unit tests for the projects built, disabled by default
          TEST: true
          PUSH: true
    
